fcheck-permission: 'FCheck.check'

messages:
  no-permissions: '§cУ вас нет прав на использование данной команды.'
  invalid-args: '§cАргументы использованы некорректно.'
  player-not-found: '§cИгрок не найден.'
  check-started: '§aПроверка начата! Игроку высланы уведомления о проверке.'
  check-start-alert: '§4Вы были вызваны на проверку, напишите свой Дискорд в чате, и мы с вами свяжемся. У вас есть 5 минут. При выходе с проверки, некорректным общением с проверяющим или других нарушениях будет блокировка.'

